name: Build and Release WordPress Plugin

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mbstring, intl
          tools: composer

      - name: Install Node dependencies
        run: npm ci

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Build plugin release
        run: npm run release

      - name: Upload Release Asset
        uses: ncipollo/release-action@v1
        with:
          artifacts: release/filo-data-broker.zip
